### ISSUE TITLE
GAN loss equation in Latex

### ISSUE THREAD

**Issue by llv22** [lipanUestc/WorkSpace#1]
Please add loss equation via Latex expression in https://github.com/lipanUestc/WorkSpace/blob/master/1%E3%80%81GAN%E5%AE%9E%E7%8E%B0MNIST.ipynb

**Comment by lipanUestc** [comment]
GAN的loss公式计算时可写为如下形式（每个batch大小为m）：
g__ loss=1/m ∑_(i=1)^m▒〖log⁡(1-D(G(z^((ⅈ) ) )))〗
d__ loss=1/m ∑_(i=1)^m▒〖[logD⁡(x^((ⅈ) ) )+log⁡(1-D(G(z^((ⅈ) ) )))]〗
GAN的loss公式说明时可写为如下形式（指明输入数据域）：
g__ loss=min⁡ E_(z~P_z (z) ) [log⁡(1-D(G(z)))]
d__ loss=max⁡ E_(x~P_data (x) ) 〖[logD(x)]+E〗_(z~P_z (z) ) [log⁡(1-D(G(z)))]

**Comment by lipanUestc** [comment]
@llv22  老师您好，我把公式写完了，放在文件五——“5、GAN的loss公式”
